### ISSUE TITLE
How to get Username?

### ISSUE THREAD

**Issue by batjko** [ggauravr/slack-terminalize#14]
Hi there,

Firstly, this is a really nice way of getting a quick slack bot running!

In my response, I'd like to mention the user who sent the command, but the param object only gives me a cryptic user ID, which I'm not sure of what use it is.

How do I get the actual username?

**Comment by ggauravr** [comment]
Hi @batjko ,

Thanks!

You can get the username from that cryptic user id using this:

```js
let user = require('slack-terminalize').getRTMClient().dataStore.getUserById(param.user)

// user.name -> username
// user.real_name -> real name
```

e.g. In the given `help.js` in `command/` directory in the [sample app](https://github.com/ggauravr/slack-sample-cli), you have a `slackTerminal` variable. So just do this wherever you have the param object:

```js
let user = slackTerminal.getRTMClient().dataStore.getUserById(param.user)

// user.name -> username
// user.real_name -> real name
```
This will give you a `user` object, which has `name` for username and `real_name` for the real name of the user.

**Comment by ggauravr** [comment]
And you can do this to actually mention a user in the response: 
```js
response += '<@'+param.user+'|'+user.name+'>'

// e.g. Hey <@U024BE7LH|bob>, did you see my file?
```

You can read more about the message formatting options here [https://api.slack.com/docs/message-formatting#linking_to_channels_and_users](https://api.slack.com/docs/message-formatting#linking_to_channels_and_users)

**Comment by batjko** [comment]
Ah, I have missed the ability to get the RTMClient directly.
Exactly what I was looking for. Many thanks for your prompt reply!
